version: "2"
services:
  budget-backend:
    container_name: budget-backend
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    environment:
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_PUBLIC_KEY: ${PLAID_PUBLIC_KEY}
      PLAID_ENV: development
      DISCOVER_ACCESS_KEY: ${DISCOVER_ACCESS_KEY}
      FCCU_ACCESS_KEY: ${FCCU_ACCESS_KEY}
      SECRET_USERNAME: ${SECRET_USERNAME}
      SECRET_PASSWORD: ${SECRET_PASSWORD}
      BUDGET_CERT_PASSWORD: ${BUDGET_CERT_PASSWORD}
      DATA_FOLDER: /data
    volumes:
      - ../data:/data
      - ../../budget-web/build:/usr/budget-web/build
    labels:
      - "traefik.http.routers.budget.rule=Host(`budget.homelab.local`)"
      - "traefik.http.services.budget.loadbalancer.server.port=3000"

networks:
  default:
    external:
      name: homelab-net
