version: "2"
services:
  budget-backend:
    container_name: budget-backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      BUDGET_FCCU_USERNAME: ${BUDGET_FCCU_USERNAME}
      BUDGET_FCCU_PASSWORD: ${BUDGET_FCCU_PASSWORD}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
