version: "2"
services:
  budget-backend:
    container_name: budget-backend
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    links:
      - mongo
    environment:
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_PUBLIC_KEY: ${PLAID_PUBLIC_KEY}
      PLAID_ENV: development
      DISCOVER_ACCESS_KEY: ${DISCOVER_ACCESS_KEY}
      FCCU_ACCESS_KEY: ${FCCU_ACCESS_KEY}
      SECRET_USERNAME: ${SECRET_USERNAME}
      SECRET_PASSWORD: ${SECRET_PASSWORD}
      BUDGET_CERT_PASSWORD: ${BUDGET_CERT_PASSWORD}
    # uncomment this command to run in debug mode
    # command:
    #   - node
    #   - "--inspect-brk=0.0.0.0"
    #   - "index.js"

    # uncomment this command to run integration tests
    # command:
    #   - npm
    #   - testIntegration
    # restart: "no"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
